### ISSUE TITLE
Clear compilation error when an `Environment` is executed but some computation in it has unsatisfied dependencies.

### ISSUE THREAD

**Issue by ldionne** [ldionne/react#1]

**Comment by ldionne** [comment]
This is addressed by using the `react::computation::strict` wrapper introduced in feb8ef4fb0ae53b82e869f62d20ce27038334c14.
